services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
